defmodule HungryEmpWeb.Location do
  @type t() :: %__MODULE__{
          id: integer(),
          applicant: String.t(),
          facility: String.t(),
          cnn: integer(),
          description: String.t(),
          address: String.t(),
          blocklot: integer(),
          block: integer(),
          lot: integer(),
          permit: String.t(),
          status: String.t(),
          food: String.t(),
          x: float(),
          y: float(),
          latitude: float(),
          longitude: float(),
          schedule: String.t(),
          hours: String.t() | nil,
          noi: String.t() | nil,
          approved: String.t() | nil,
          received: Date.t(),
          prior_permit: boolean(),
          expires: Date.t(),
          location: String.t(),
          fire_districts: integer() | nil,
          police_districts: integer() | nil,
          supervisor_districts: integer() | nil,
          zip_codes: integer() | nil,
          neighborhoods: integer() | nil
        }

  @enforce_keys [
    :id,
    :applicant,
    :facility,
    :cnn,
    :description,
    :address,
    :blocklot,
    :block,
    :lot,
    :permit,
    :status,
    :food,
    :x,
    :y,
    :latitude,
    :longitude,
    :schedule,
    :hours,
    :noi,
    :approved,
    :received,
    :prior_permit,
    :expires,
    :location,
    :fire_districts,
    :police_districts,
    :supervisor_districts,
    :zip_codes,
    :neighborhoods
  ]
  defstruct(
    id: nil,
    applicant: nil,
    facility: nil,
    cnn: nil,
    description: nil,
    address: nil,
    blocklot: nil,
    block: nil,
    lot: nil,
    permit: nil,
    status: nil,
    food: nil,
    x: nil,
    y: nil,
    latitude: nil,
    longitude: nil,
    schedule: nil,
    hours: nil,
    noi: nil,
    approved: nil,
    received: nil,
    prior_permit: nil,
    expires: nil,
    location: nil,
    fire_districts: nil,
    police_districts: nil,
    supervisor_districts: nil,
    zip_codes: nil,
    neighborhoods: nil
  )
end
